name: Update

on: 
  repository_dispatch:  # 允许外部事件触发工作流
  workflow_dispatch:    # 允许手动触发工作流

  # 定时触发编译
  schedule:
    - cron: 0 23 * * *  # 每天晚上 11 点触发

jobs:
  Update:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Clone Repository  # 克隆代码库
      uses: actions/checkout@v4  # 使用官方的 checkout Action

    - name: 设置 git 配置和时区  # 设置 git 用户信息和时区
      run: |
        git config --global user.email "${{ secrets.GH_MAIL }}"  # 设置 git 邮箱
        git config --global user.name "${{ secrets.GH_NAME }}"    # 设置 git 用户名
        sudo timedatectl set-timezone "Asia/Shanghai"  # 设置时区为上海

    - name: 删除工作流运行记录  # 清理旧的工作流运行记录
      uses: Mattraks/delete-workflow-runs@main  # 使用 Mattraks 提供的删除工作流运行的 GitHub Action
      continue-on-error: true  # 如果此步骤失败，后续步骤仍然会继续执行
      with:
        retain_days: 1  # 保留最近 1 天的运行记录
        keep_minimum_runs: 0  # 最少保留的运行记录数量为 0

    - name: 更新代码库  # 更新多个代码库
      run: |

        # 删除目录
        rm -rf ./vpn
        rm -rf ./nas
        rm -rf ./iStore
        rm -rf ./docker
        rm -rf ./dns
        rm -rf ./bot
        rm -rf ./dns
        rm -rf ./ad
        rm -rf ./vpn/luci-app-openclash


        # 克隆新项目
        
        git clone https://github.com/rufengsuixing/luci-app-adguardhome ./dns/luci-app-adguardhome
        rm -rf ./dns/luci-app-adguardhome/README.md
        rm -rf ./dns/luci-app-adguardhome/.github
        rm -rf ./dns/luci-app-adguardhome/.git
        rm -rf ./dns/luci-app-adguardhome/.gitattributes
        rm -rf ./dns/luci-app-adguardhome/.gitignore

        git clone https://github.com/sirpdboy/luci-app-ddns-go ./dns/ddnsgo
        mv ./dns/ddnsgo/ddns-go ./dns/ddns-go
        mv ./dns/ddnsgo/luci-app-ddns-go ./dns/luci-app-ddns-go
        rm -rf ./dns/ddnsgo
        
         git clone https://github.com/zzsj0928/luci-app-pushbot ./bot/luci-app-pushbot
        rm -rf ./bot/luci-app-pushbot/.git
        rm -rf ./bot/luci-app-pushbot/README.md
        rm -rf ./bot/luci-app-pushbot/.github
        
         git clone https://github.com/tty228/luci-app-wechatpush ./bot/luci-app-wechatpush
        rm -rf ./bot/luci-app-wechatpush/README.md
        rm -rf ./bot/luci-app-wechatpush/README_en.md
        rm -rf ./bot/luci-app-wechatpush/.github
        rm -rf ./bot/luci-app-wechatpush/.git
        
         git clone https://github.com/ilxp/luci-app-ikoolproxy ./ad/luci-app-ikoolproxy
        rm -rf ./ad/luci-app-ikoolproxy/.github
        rm -rf ./ad/luci-app-ikoolproxy/.git
        rm -rf ./ad/luci-app-ikoolproxy/change.log
        rm -rf ./ad/luci-app-ikoolproxy/development.doc
        rm -rf ./ad/luci-app-ikoolproxy/README.md

         git clone https://github.com/linkease/nas-packages-luci ./iStore/nas-packages-luci
        mv ./iStore/nas-packages-luci/luci ./iStore/luci
        rm -rf ./iStore/nas-packages-luci
        rm -rf ./iStore/nas-packages-luci/.github
        rm -rf ./iStore/nas-packages-luci/.git
        
         git clone https://github.com/linkease/nas-packages ./iStore/nas-packages
        mv ./iStore/nas-packages/multimedia/ffmpeg-remux ./iStore/nas-packages/
        mv ./iStore/nas-packages/network/services/* ./iStore/nas-packages/
        rm -rf ./iStore/nas-packages/multimedia
        rm -rf ./iStore/nas-packages/network
        rm -rf ./iStore/nas-packages/.git
        rm -rf ./iStore/nas-packages/.github
        rm -rf ./iStore/nas-packages/README.md
        
         git clone https://github.com/linkease/istore ./iStore/iStore
        rm -rf ./iStore/iStore/.github
        rm -rf ./iStore/iStore/.git
        rm -rf ./iStore/iStore/README.md
        rm -rf ./iStore/iStore/README.en.md
        rm -rf ./iStore/iStore/LICENSE
        mv ./iStore/iStore/luci/*  ./iStore/luci/
        rm -rf ./iStore/iStore

         git clone https://github.com/linkease/istore-ui ./iStore/istore-ui
        mv ./iStore/istore-ui/app-store-ui ./iStore/luci/app-store-ui
        rm -rf ./iStore/istore-ui  

         git clone https://github.com/jerrykuku/go-aliyundrive-webdav ./nas/go-aliyundrive-webdav
        rm -rf ./nas/go-aliyundrive-webdav/.git
        rm -rf ./nas/go-aliyundrive-webdav/.github
        rm -rf ./nas/go-aliyundrive-webdav/README.md
        
         git clone https://github.com/jerrykuku/luci-app-go-aliyundrive-webdav ./nas/luci-app-go-aliyundrive-webdav
        rm -rf ./nas/luci-app-go-aliyundrive-webdav/.git
        rm -rf ./nas/luci-app-go-aliyundrive-webdav/.github
        rm -rf ./nas/luci-app-go-aliyundrive-webdav/README.md

         git clone https://github.com/xiaorouji/openwrt-passwall-packages ./vpn
        rm -rf ./vpn/.github
        rm -rf ./vpn/.git
        rm -rf ./vpn/chinadns-ng

        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git ./theme/luci-theme-argon
        rm -rf ./theme/luci-theme-argon/.github
        rm -rf ./theme/luci-theme-argon/.git
        rm -rf ./theme/luci-theme-argon/.gitignore
        rm -rf ./theme/luci-theme-argon/LICENSE
        rm -rf ./theme/luci-theme-argon/README.md
        rm -rf ./theme/luci-theme-argon/README_ZH.md
        rm -rf ./theme/luci-theme-argon/RELEASE.md
        rm -rf ./theme/luci-theme-argon/RELEASE_ZH.md

        git clone -b 18.06 https://github.com/jerrykuku/luci-app-argon-config.git ./theme/luci-app-argon-config
        rm -rf ./theme/luci-app-argon-config/LICENSE
        rm -rf ./theme/luci-app-argon-config/README.md
        rm -rf ./theme/luci-app-argon-config/README_ZH.md
        rm -rf ./theme/luci-app-argon-config/.git
        rm -rf ./theme/luci-app-argon-config/.github
        

         git clone https://github.com/fw876/helloworld ./vpn/helloworld
        mv ./vpn/helloworld/redsocks2 ./vpn/redsocks2
        mv ./vpn/helloworld/lua-neturl ./vpn/lua-neturl
        mv ./vpn/helloworld/shadow-tls ./vpn/shadow-tls
        mv ./vpn/helloworld/luci-app-ssr-plus ./vpn/luci-app-ssr-plus
        rm -rf ./vpn/gn
        rm -rf ./vpn/naiveproxy
        mv ./vpn/helloworld/gn ./vpn/gn
        mv ./vpn/helloworld/naiveproxy ./vpn/naiveproxy
        rm -rf ./vpn/helloworld
    
         git clone https://github.com/xiaorouji/openwrt-passwall ./vpn/passwall
         git clone https://github.com/xiaorouji/openwrt-passwall2 ./vpn/passwall2
        mv ./vpn/passwall/luci-app-passwall ./vpn/luci-app-passwall
        mv ./vpn/passwall2/luci-app-passwall2 ./vpn/luci-app-passwall2
        rm -rf ./vpn/passwall
        rm -rf ./vpn/passwall2

        git clone --depth=1 https://github.com/vernesong/OpenClash.git -b dev
        rm -rf ./OpenClash/.git
        rm -rf ./OpenClash/.github
        rm -rf ./OpenClash/README.md
        mv ./OpenClash/luci-app-openclash ./vpn/luci-app-openclash
        rm -rf ./OpenClash
        
         git clone https://github.com/kenzok8/openwrt-packages ./op-mosdns

        mv ./op-mosdns/smartdns ./dns/smartdns
        mv ./op-mosdns/luci-app-smartdns ./dns/luci-app-smartdns
        mv ./op-mosdns/luci-app-aliddns ./dns/luci-app-aliddns

        mv ./op-mosdns/alist ./nas/alist
        mv ./op-mosdns/luci-app-alist ./nas/luci-app-alist
        mv ./op-mosdns/filebrowser ./nas/filebrowser
        mv ./op-mosdns/luci-app-filebrowser ./nas/luci-app-filebrowser
        mv ./op-mosdns/luci-app-advanced ./nas/luci-app-advanced


        mv ./op-mosdns/gost ./vpn/gost
        mv ./op-mosdns/luci-app-gost ./vpn/luci-app-gost


        rm -rf ./op-mosdns

        git clone https://github.com/lisaac/luci-app-dockerman ./other/dockerman
        mv ./other/dockerman/applications/luci-app-dockerman ./other/luci-app-dockerman
        rm -rf ./other/dockerman

        
    - name: 提交更改并推送到远程仓库
      run: |
        echo "Adding changes to git..."
        git add .
        git commit -m "Update scripts"
        echo "Pushing changes to GitHub..."
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
